#pragma once
#include <iostream>
#include <stdexcept>
//#include <cstdlib>
#include <ctime>
#include <string>
#include <sstream>
#include <fstream>
#include <algorithm>
#include <vector>
#include <map>
#include <iterator>
#include <math.h>
#include <SDL.h>
#include <SDL_image.h>
#include <SDL_mixer.h>
#include <SDL_ttf.h>
#include <windows.h>
#include <commctrl.h>
#include <stdlib.h>
#include <tchar.h>
#include "SDL_thread.h"
#include "SDL_timer.h"

